export const objects = [
  {
    rx: 0,
    ry: 0,
    src: 'https://cdn.husble.com/husblizer/test/Blank_Base_-_Shirt_-_4050_x_4650-1629429141999.png',
    top: 449,
    fill: '#fff',
    left: 256,
    type: 'backgroundPro',
    angle: 0,
    flipX: false,
    flipY: false,
    skewX: 0,
    skewY: 0,
    width: 4050,
    height: 4650,
    scaleX: 1,
    scaleY: 1,
    shadow: null,
    stroke: '#bbb',
    opacity: 1,
    originX: 'center',
    originY: 'center',
    version: '4.3.1',
    visible: true,
    fillRule: 'nonzero',
    borderColor: 'transparent',
    borderWidth: 0,
    strokeWidth: 0,
    strokeLineCap: 'butt',
    strokeUniform: true,
    strokeLineJoin: 'miter',
    backgroundColor: '',
    strokeDashArray: [7, 7],
    strokeDashOffset: 0,
    strokeMiterLimit: 4,
    borderScaleFactor: 0,
    globalCompositeOperation: 'source-over',
  },
];
